version: '3.4'

services:
  productservice:
    image: productservice
    build:
      context: ./ProductSerivceReal
    ports:
      - "8000:80"
    networks:
      - microservicesnetwork

  orderservice:
    image: orderservice
    build:
      context: ./OrderService
    ports:
      - "8001:80"
    networks:
      - microservicesnetwork

networks:
  microservicesnetwork:
    driver: bridge